version: "3.7"
services:
  app:
    image: rust:1.59.0
    restart: always
    command: sh -c "RUST_LOG=debug cargo run --release > log.txt"
    working_dir: /app
    volumes:
      - ./:/app

  skytable:
    image: skytable/sdb
    restart: always
    ports:
     - "2003:2003"
    working_dir: /skytable-db
    volumes:
      - skytable-db:/skytable-db

  postgresql:
    image: postgres:13.6
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - psql-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  psql-db:
  skytable-db: