version: "3.7"
services:
  app:
    image: rust:1.61.0
    restart: always
    command: sh -c "export TELOXIDE_TOKEN=5554390902:AAHlRMql--ZbLHEybzEY1MK_r19b9EEU6_I && RUST_LOG=debug cargo run --release"
    working_dir: /app
    volumes:
      - ./:/app

  skytable:
    image: stepanovdenis/skytable
    restart: always

  postgresql:
    image: postgres:13.6
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - psql-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  psql-db:
  skytable-db: