version: "3.7"
services:
  app:
    image: rust:1.62.0
    restart: always
    command: sh -c "RUST_LOG=info cargo run --release"
    working_dir: /app
    volumes:
      - ./:/app

  postgresql:
    image: postgres:13.6
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - psql-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  psql-db: