version: "3.7"
services:
  app:
    image: rust:latest
    restart: always
    command: sh -c "RUST_LOG=debug cargo run --release"
    ports:
      - "5432:5432"
      - "2003:2003"
    working_dir: /app
    volumes:
      - ./:/app

  skytable:
    image: skytable/sdb:latest
    restart: always
    working_dir: /skytable-db
    volumes:
      - skytable-db:/skytable-db

  postgresql:
    image: postgres:13.6
    restart: always
    volumes:
      - psql-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  psql-db:
  skytable-db: