[tasks.run_clean]
script = "cargo clean"

[tasks.run_fmt]
script = "cargo fmt"

[tasks.run_test]
script = "cargo test"

[tasks.run_build]
script = "cargo build --release"

[tasks.run]
script = "RUST_LOG=debug cargo run --release > log.txt"

[tasks.app]
dependencies = [
    "run_clean",
    "run_fmt",
    "run_test",
    "run_build",
    "run"
]