[tasks.run_clean]
script = "cargo clean"

[tasks.run_fmt]
script = "cargo fmt"

[tasks.run_clippy]
script = "cargo clippy"

[tasks.run_test]
script = "cargo test"

[tasks.run_build]
script = "cargo build --release"

[tasks.doc]
script = "cargo doc --no-deps"

[tasks.copy_docs]
script = [
    "mkdir -p ./docs",
    "mv ./target/doc/* ./docs"
]

[tasks.run]
script = "RUST_LOG=debug cargo run --release > log.txt"

[tasks.app]
dependencies = [
    "run_clean",
    "run_fmt",
    "run_clippy",
    "test",
    "run_build",
    "doc",
    "copy_docs",
    "run"
]