[env]
# PostgreSQL settings
POSTGRES_USERNAME = "postgres"
POSTGRES_PASSWORD = "mysecretpassword"
POSTGRES_DB = "postgres"
POSTGRES_HOSTNAME = "postgresql"
POSTGRES_PORT = "5432"


# Alert messages for sms gateway
# Sms gateway string connection
GATEWAY_STR_CONNECTION = "https://api-mapper.clicksend.com/http/v2/send.php?method=http&username=development-service@yandex.ru&key=1E82A334-89D8-985C-526B-712DB70A713D&to=+79139402913&message="

# The text of the SMS-message about the generator operation error
SMS_GEN_WORK_ERR = "Авария!+Генератор+неисправен!+Срочно+произведите+сервисные+работы!"

# The text of the SMS-message about the resumption of the generator operation
SMS_GEN_WORK_RESTORED = "Работоспособность+генератора+в+режиме+трансляции+питания+от+электросети+восстановлена.+Генератор+исправен.+Генератор+работает."

# The text of the SMS-message about the successful start of the generator
SMS_START_GEN_OK = "Сбой+питания+от+электросети.+Успешный+старт+генератора."

# Text of SMS-message about generator start error
SMS_START_GEN_ERR = "Сбой+питания+от+электросети.+Сбой+старта+генератора."

# The text of the SMS-message about the resumption of power supply from the network and the serviceability of the generator
SMS_POW_RESTORED_GEN_OK = "Питание+от+электросети+восстановлено.+Генератор+исправен.+Генератор+работает."

# The text of the SMS-message about the resumption of power supply from the network and the failure of the generator
SMS_POW_RESTORED_GEN_ERR = "Питание+от+электросети+восстановлено.+Генератор+неисправен.+Генератор+не+работает."


# Alert messages for Telegram-bot
# The text of the Telegram-message about the generator operation error
TG_GEN_WORK_ERR = "Авария! Генератор неисправен! Срочно произведите сервисные работы!"

# The text of the Telegram-message about the resumption of the generator operation
TG_GEN_WORK_RESTORED = "Работоспособность генератора в режиме трансляции питания от электросети восстановлена.\nГенератор+исправен.\nГенератор работает."

# The text of the Telegram-message about the successful start of the generator
TG_START_GEN_OK = "Сбой питания от электросети.\nУспешный старт генератора."

# Text of Telegram-message about generator start error
TG_START_GEN_ERR = "Сбой питания от электросети.\nСбой старта генератора."

# The text of the Telegram-message about the resumption of power supply from the network and the serviceability of the generator
TG_POW_RESTORED_GEN_OK = "Питание от электросети восстановлено.\nГенератор исправен.\nГенератор работает."

# The text of the Telegram-message about the resumption of power supply from the network and the failure of the generator
TG_POW_RESTORED_GEN_ERR = "Питание от электросети восстановлено.\nГенератор неисправен.\nГенератор не работает."


# IP adress PLC TRIM5
IP_TRIM5 = "10.54.52.201:502"

# mains_power_supply_response
MAINS_POWER_SUPPLY = "2"

# start_generator
START_GENERATOR = "3"

# generator_faulty
GENERATOR_FAULTY = "5"

# generator_work
TRANSMITTED_WORK = "6"

# connection
CONNECTION = "19"

# load
LOAD = "4"

# phyto_lighting_1
PHYTO_LIGHTING_1 = "7"

# phyto_lighting_2
PHYTO_LIGHTING_2 = "8"

# phyto_lighting_3
PHYTO_LIGHTING_3 = "9"

# phyto_lighting_4
PHYTO_LIGHTING_4 = "10"

# fan
FAN = "11"

# automatic_watering_1
AUTOMATIC_WATERING_1 = "12"

# automatic_watering_2
AUTOMATIC_WATERING_2 = "13"

# automatic_watering_3
AUTOMATIC_WATERING_3 = "14"

# temperature_indoor
TEMPERATURE_INDOOR = "15"

# humidity_indoor
HUMIDITY_INDOOR = "16"

# illumination_indoor
ILLUMINATION_INDOOR = "17"

# illumination_outdoor
ILLUMINATION_OUTDOOR = "18"